//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../../../../sequelbook/sequelbook/events/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "sequelbook:connection-state-changed": $$createType0,
        "sequelbook:notification": $$createType1,
        "sequelbook:query-cancelled": $$createType2,
        "sequelbook:query-completed": $$createType3,
        "sequelbook:query-failed": $$createType4,
        "sequelbook:query-started": $$createType5,
    }));
}

// Private type creation functions
const $$createType0 = events$0.ConnectionStateChangedPayload.createFrom;
const $$createType1 = events$0.NotificationPayload.createFrom;
const $$createType2 = events$0.QueryCancelledPayload.createFrom;
const $$createType3 = events$0.QueryCompletedPayload.createFrom;
const $$createType4 = events$0.QueryFailedPayload.createFrom;
const $$createType5 = events$0.QueryStartedPayload.createFrom;

configure();
