// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as events$0 from "../../../../sequelbook/sequelbook/events/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "sequelbook:connection-state-changed": events$0.ConnectionStateChangedPayload;
            "sequelbook:notification": events$0.NotificationPayload;
            "sequelbook:query-cancelled": events$0.QueryCancelledPayload;
            "sequelbook:query-completed": events$0.QueryCompletedPayload;
            "sequelbook:query-failed": events$0.QueryFailedPayload;
            "sequelbook:query-started": events$0.QueryStartedPayload;
        }
    }
}
