// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookService exposes book management to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as book$0 from "../core/book/models.js";

/**
 * AddBlock inserts a new block into a section at the given position.
 * If position < 0 or >= len(blocks), the block is appended.
 */
export function AddBlock(bookID: string, chapterID: string, sectionID: string, blockType: book$0.BlockType, position: number): $CancellablePromise<book$0.Block | null> {
    return $Call.ByID(3255065554, bookID, chapterID, sectionID, blockType, position).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddChapter appends a new chapter to the book.
 */
export function AddChapter(bookID: string, title: string): $CancellablePromise<book$0.Chapter | null> {
    return $Call.ByID(606647330, bookID, title).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * AddSection appends a new section to the given chapter.
 */
export function AddSection(bookID: string, chapterID: string, title: string): $CancellablePromise<book$0.Section | null> {
    return $Call.ByID(2626020284, bookID, chapterID, title).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CloseBook removes the book from the open books map.
 */
export function CloseBook(bookID: string): $CancellablePromise<void> {
    return $Call.ByID(180959975, bookID);
}

/**
 * CreateBook makes a new empty book with the given title.
 * Auto-assigns a file path in the books directory for persistence.
 */
export function CreateBook(title: string): $CancellablePromise<book$0.OpenBook | null> {
    return $Call.ByID(3677380935, title).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DeleteBook permanently deletes the book file from disk and removes it from memory.
 */
export function DeleteBook(bookID: string): $CancellablePromise<void> {
    return $Call.ByID(2668824628, bookID);
}

/**
 * GetBook retrieves an open book by ID.
 */
export function GetBook(bookID: string): $CancellablePromise<book$0.OpenBook | null> {
    return $Call.ByID(1039180295, bookID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListBooks returns all currently open books.
 */
export function ListBooks(): $CancellablePromise<(book$0.OpenBook | null)[]> {
    return $Call.ByID(862697484).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * LoadBooksDir loads all .sql files from the configured books directory.
 */
export function LoadBooksDir(): $CancellablePromise<void> {
    return $Call.ByID(3590730111);
}

/**
 * MoveBlock moves a block to a new position within its section.
 * newPosition is 0-based and clamped to valid range.
 */
export function MoveBlock(bookID: string, chapterID: string, sectionID: string, blockID: string, newPosition: number): $CancellablePromise<void> {
    return $Call.ByID(1635296364, bookID, chapterID, sectionID, blockID, newPosition);
}

/**
 * OpenBook reads a .sql file, parses it, and registers the book.
 */
export function OpenBook(path: string): $CancellablePromise<book$0.OpenBook | null> {
    return $Call.ByID(4260866795, path).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * OpenFileDialog shows a native open-file picker filtered to *.sql files.
 * Returns the selected path, or an empty string if cancelled.
 */
export function OpenFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(278755920);
}

/**
 * RemoveBlock removes a block from a section.
 */
export function RemoveBlock(bookID: string, chapterID: string, sectionID: string, blockID: string): $CancellablePromise<void> {
    return $Call.ByID(3480055143, bookID, chapterID, sectionID, blockID);
}

/**
 * RemoveChapter removes a chapter from the book.
 */
export function RemoveChapter(bookID: string, chapterID: string): $CancellablePromise<void> {
    return $Call.ByID(1155823995, bookID, chapterID);
}

/**
 * RemoveSection removes a section from the given chapter.
 */
export function RemoveSection(bookID: string, chapterID: string, sectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3384642749, bookID, chapterID, sectionID);
}

/**
 * RenameBook updates the book's title in memory and marks it dirty.
 */
export function RenameBook(bookID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2107630693, bookID, title);
}

/**
 * RenameChapter sets a new title on a chapter.
 */
export function RenameChapter(bookID: string, chapterID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(154453301, bookID, chapterID, title);
}

/**
 * RenameSection sets a new title on a section.
 */
export function RenameSection(bookID: string, chapterID: string, sectionID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(462136983, bookID, chapterID, sectionID, title);
}

/**
 * ReorderChapters reorders chapters according to the given slice of IDs.
 * All existing chapter IDs must be present; extras are ignored.
 */
export function ReorderChapters(bookID: string, chapterIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1490111387, bookID, chapterIDs);
}

/**
 * SaveAllDirty persists all open books that have been modified since last save.
 */
export function SaveAllDirty(): $CancellablePromise<void> {
    return $Call.ByID(1900200070);
}

/**
 * SaveBook serializes and writes the book to its current file path.
 * Returns an error if the book has no path (use SaveBookAs instead).
 */
export function SaveBook(bookID: string): $CancellablePromise<void> {
    return $Call.ByID(512458174, bookID);
}

/**
 * SaveBookAs serializes and writes the book to the given path.
 */
export function SaveBookAs(bookID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2285877050, bookID, path);
}

/**
 * SaveFileDialog shows a native save-file picker filtered to *.sql files.
 * Returns the chosen path, or an empty string if cancelled.
 */
export function SaveFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(2431582401);
}

/**
 * UpdateBlock replaces a block's content.
 */
export function UpdateBlock(bookID: string, chapterID: string, sectionID: string, blockID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3589801280, bookID, chapterID, sectionID, blockID, content);
}

/**
 * UpdateBlockPageSize sets a query block's page size for result pagination.
 */
export function UpdateBlockPageSize(bookID: string, chapterID: string, sectionID: string, blockID: string, pageSize: number): $CancellablePromise<void> {
    return $Call.ByID(3642658538, bookID, chapterID, sectionID, blockID, pageSize);
}

// Private type creation functions
const $$createType0 = book$0.Block.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = book$0.Chapter.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = book$0.Section.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = book$0.OpenBook.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
