// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService exposes connection management to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../core/connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../core/settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect establishes a new database connection.
 * Returns the connection ID on success.
 */
export function Connect(config: connection$0.ConnectionConfig): $CancellablePromise<string> {
    return $Call.ByID(3145002171, config);
}

/**
 * DeleteConnection removes a saved connection by ID.
 */
export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(2209878964, id);
}

/**
 * Disconnect closes the named connection.
 */
export function Disconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(4146857181, connID);
}

/**
 * GetConnectionStatus returns the current connection state.
 */
export function GetConnectionStatus(): $CancellablePromise<$models.ConnectionStatus> {
    return $Call.ByID(3126007175).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListSavedConnections returns all saved connection entries sorted by name.
 */
export function ListSavedConnections(): $CancellablePromise<settings$0.ConnectionEntry[]> {
    return $Call.ByID(2650515463).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveConnection adds or updates a saved connection entry.
 * If entry.ID is empty, a new ID is assigned. Returns the entry with ID set.
 */
export function SaveConnection(entry: settings$0.ConnectionEntry): $CancellablePromise<settings$0.ConnectionEntry | null> {
    return $Call.ByID(2665198950, entry).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * TestConnection validates credentials without persisting a connection.
 */
export function TestConnection(config: connection$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(1444596147, config);
}

// Private type creation functions
const $$createType0 = $models.ConnectionStatus.createFrom;
const $$createType1 = settings$0.ConnectionEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType1);
