// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as result$0 from "../core/result/models.js";

/**
 * ConnectionStatus is the JSON shape returned by GetConnectionStatus.
 */
export class ConnectionStatus {
    "connId": string;
    "state": string;
    "connected": boolean;

    /** Creates a new ConnectionStatus instance. */
    constructor($$source: Partial<ConnectionStatus> = {}) {
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus($$parsedSource as Partial<ConnectionStatus>);
    }
}

/**
 * QueryResponse is the value returned by ExecuteQuery.
 * It bundles the result ID with the first page of rows and result metadata
 * so the frontend can display results immediately without a follow-up call.
 */
export class QueryResponse {
    "resultId": string;
    "page": result$0.Page | null;
    "meta": result$0.ResultMeta | null;

    /** Creates a new QueryResponse instance. */
    constructor($$source: Partial<QueryResponse> = {}) {
        if (!("resultId" in $$source)) {
            this["resultId"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = null;
        }
        if (!("meta" in $$source)) {
            this["meta"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResponse {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("page" in $$parsedSource) {
            $$parsedSource["page"] = $$createField1_0($$parsedSource["page"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField2_0($$parsedSource["meta"]);
        }
        return new QueryResponse($$parsedSource as Partial<QueryResponse>);
    }
}

// Private type creation functions
const $$createType0 = result$0.Page.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = result$0.ResultMeta.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
