// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService exposes query execution to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as result$0 from "../core/result/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelQuery attempts to cancel a running query by its query ID.
 */
export function CancelQuery(queryID: string): $CancellablePromise<void> {
    return $Call.ByID(3462346035, queryID);
}

/**
 * DisposeResult frees memory for a stored result set.
 */
export function DisposeResult(resultID: string): $CancellablePromise<void> {
    return $Call.ByID(2332390237, resultID);
}

/**
 * ExecuteQuery runs a SQL query against the given connection.
 * 
 * Event sequence:
 *  1. QueryStarted — emitted before execution (queryID is unknown at this point,
 *     so an empty string is used; the frontend uses it as a loading signal only).
 *  2. QueryCompleted — emitted on success with the real queryID and stats.
 *  3. QueryFailed / QueryCancelled — emitted on failure.
 * 
 * On success the result is stored in the handler and the first page + metadata
 * are returned in QueryResponse so the frontend needs no follow-up call.
 */
export function ExecuteQuery(connID: string, sql: string): $CancellablePromise<$models.QueryResponse | null> {
    return $Call.ByID(469082650, connID, sql).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetResultMeta returns column metadata and statistics for a stored result set.
 */
export function GetResultMeta(resultID: string): $CancellablePromise<result$0.ResultMeta | null> {
    return $Call.ByID(1915932857, resultID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetResultPage returns a paginated window of rows for an existing result set.
 */
export function GetResultPage(resultID: string, offset: number, limit: number): $CancellablePromise<result$0.Page | null> {
    return $Call.ByID(1802277351, resultID, offset, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.QueryResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = result$0.ResultMeta.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = result$0.Page.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
