// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemaService exposes schema introspection to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../core/schema/models.js";

/**
 * GetCompletionSchema returns a flat map of table names to column name lists
 * for use in CodeMirror SQL autocompletion. Keys use "schema.table" format for
 * non-default schemas (public for Postgres, main for SQLite).
 */
export function GetCompletionSchema(connID: string): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(2227417781, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListColumns returns all columns for the given schema.table.
 */
export function ListColumns(connID: string, schemaName: string, tableName: string): $CancellablePromise<schema$0.Column[]> {
    return $Call.ByID(492722507, connID, schemaName, tableName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListTables returns all tables for the given connection.
 * If schema is non-empty, filters by that schema.
 */
export function ListTables(connID: string, schemaName: string): $CancellablePromise<schema$0.Table[]> {
    return $Call.ByID(3830791845, connID, schemaName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * PreviewTableQuery returns a SQL query to fetch the first N rows from a table.
 * The query uses database-appropriate quoting for identifiers.
 */
export function PreviewTableQuery(connID: string, schemaName: string, tableName: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(3079779652, connID, schemaName, tableName, limit);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = schema$0.Column.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = schema$0.Table.createFrom;
const $$createType5 = $Create.Array($$createType4);
