// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes app configuration to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../core/settings/models.js";

/**
 * GetBooksDir returns the resolved books directory path.
 */
export function GetBooksDir(): $CancellablePromise<string> {
    return $Call.ByID(3252863963);
}

/**
 * GetConfig returns the current app configuration.
 */
export function GetConfig(): $CancellablePromise<settings$0.Config> {
    return $Call.ByID(1558848164).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadEditorState reads the persisted editor state from disk.
 * Returns empty string if the file does not exist (first run).
 */
export function LoadEditorState(): $CancellablePromise<string> {
    return $Call.ByID(624579536);
}

/**
 * SaveEditorState persists the editor layout (tabs, panes, sidebar, selection) to disk.
 */
export function SaveEditorState(state: string): $CancellablePromise<void> {
    return $Call.ByID(1340561187, state);
}

/**
 * UpdateConfig replaces the app configuration and persists it to disk.
 */
export function UpdateConfig(cfg: settings$0.Config): $CancellablePromise<void> {
    return $Call.ByID(204499237, cfg);
}

// Private type creation functions
const $$createType0 = settings$0.Config.createFrom;
