// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewMenu(arg1) {
  return window['go']['backend']['Backend']['NewMenu'](arg1);
}
