// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['backend']['ConnectionStore']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['backend']['ConnectionStore']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['backend']['ConnectionStore']['Get'](arg1);
}

export function GetAll() {
  return window['go']['backend']['ConnectionStore']['GetAll']();
}

export function Query(arg1, arg2) {
  return window['go']['backend']['ConnectionStore']['Query'](arg1, arg2);
}

export function Update(arg1, arg2) {
  return window['go']['backend']['ConnectionStore']['Update'](arg1, arg2);
}
