// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Add(arg1:backend.ConnectionCreateData):Promise<backend.Connection>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<backend.Connection|boolean>;

export function GetAll():Promise<Array<backend.Connection>>;

export function Query(arg1:string,arg2:string):Promise<string>;

export function Update(arg1:string,arg2:backend.Connection):Promise<void>;
