// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {books} from '../models';

export function CreateBook(arg1:books.BookData):Promise<books.Book>;

export function CreateCell(arg1:string,arg2:books.BlockType):Promise<books.Cell>;

export function DeleteBook(arg1:string):Promise<void>;

export function DuplicateBook(arg1:string):Promise<books.Book>;

export function GetBook(arg1:string):Promise<books.Book>;

export function ListBooks():Promise<Array<books.Book>>;

export function LoadBooks():Promise<void>;

export function UpdateBook(arg1:string,arg2:books.BookData):Promise<books.Book>;
