// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['books']['BooksStore']['CreateBook'](arg1);
}

export function CreateCell(arg1, arg2) {
  return window['go']['books']['BooksStore']['CreateCell'](arg1, arg2);
}

export function DeleteBook(arg1) {
  return window['go']['books']['BooksStore']['DeleteBook'](arg1);
}

export function GetBook(arg1) {
  return window['go']['books']['BooksStore']['GetBook'](arg1);
}

export function ListBooks() {
  return window['go']['books']['BooksStore']['ListBooks']();
}

export function LoadBooks() {
  return window['go']['books']['BooksStore']['LoadBooks']();
}

export function UpdateBook(arg1, arg2) {
  return window['go']['books']['BooksStore']['UpdateBook'](arg1, arg2);
}
