// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionConfig holds the parameters needed to connect to a database.
 * Type defaults to "postgres" when empty. For SQLite, Database is the file path.
 */
export class ConnectionConfig {
    /**
     * postgres | mysql | sqlite; default postgres
     */
    "type": string;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "password": string;

    /**
     * disable | require | verify-ca | verify-full (PostgreSQL only)
     */
    "sslMode": string;
    "ssh"?: SSHTunnelConfig | null;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField7_0($$parsedSource["ssh"]);
        }
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

/**
 * SSHAuthMethod identifies how to authenticate with the SSH server.
 */
export enum SSHAuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SSHAuthKey = "key",
    SSHAuthPassword = "password",
    SSHAuthAgent = "agent",
};

/**
 * SSHTunnelConfig holds the parameters for an SSH tunnel.
 */
export class SSHTunnelConfig {
    "host": string;

    /**
     * default 22
     */
    "port": number;
    "user": string;

    /**
     * key | password | agent
     */
    "authMethod": SSHAuthMethod;

    /**
     * file path (authMethod=key)
     */
    "privateKey": string;

    /**
     * key passphrase (authMethod=key)
     */
    "passphrase": string;

    /**
     * SSH password (authMethod=password)
     */
    "password": string;

    /**
     * DB host from SSH server's perspective
     */
    "remoteHost": string;

    /**
     * DB port from SSH server's perspective
     */
    "remotePort": number;

    /** Creates a new SSHTunnelConfig instance. */
    constructor($$source: Partial<SSHTunnelConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = SSHAuthMethod.$zero;
        }
        if (!("privateKey" in $$source)) {
            this["privateKey"] = "";
        }
        if (!("passphrase" in $$source)) {
            this["passphrase"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("remoteHost" in $$source)) {
            this["remoteHost"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHTunnelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHTunnelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHTunnelConfig($$parsedSource as Partial<SSHTunnelConfig>);
    }
}

// Private type creation functions
const $$createType0 = SSHTunnelConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
