// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * ConnectionStateChangedPayload is emitted when a connection's lifecycle state
 * changes. State is a plain string (e.g. "connected") to avoid importing core/.
 */
export class ConnectionStateChangedPayload {
    "connId": string;
    "state": string;
    "error"?: string;

    /** Creates a new ConnectionStateChangedPayload instance. */
    constructor($$source: Partial<ConnectionStateChangedPayload> = {}) {
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStateChangedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStateChangedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStateChangedPayload($$parsedSource as Partial<ConnectionStateChangedPayload>);
    }
}

/**
 * NotificationPayload is emitted for user-visible notifications (toasts, etc.).
 */
export class NotificationPayload {
    "severity": Severity;
    "title": string;
    "message": string;

    /** Creates a new NotificationPayload instance. */
    constructor($$source: Partial<NotificationPayload> = {}) {
        if (!("severity" in $$source)) {
            this["severity"] = Severity.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationPayload($$parsedSource as Partial<NotificationPayload>);
    }
}

/**
 * QueryCancelledPayload is emitted when a query is cancelled by the user.
 */
export class QueryCancelledPayload {
    "queryId": string;

    /** Creates a new QueryCancelledPayload instance. */
    constructor($$source: Partial<QueryCancelledPayload> = {}) {
        if (!("queryId" in $$source)) {
            this["queryId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryCancelledPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryCancelledPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryCancelledPayload($$parsedSource as Partial<QueryCancelledPayload>);
    }
}

/**
 * QueryCompletedPayload is emitted when a query finishes successfully.
 * Duration is in nanoseconds (time.Duration = int64); the frontend converts.
 */
export class QueryCompletedPayload {
    "queryId": string;
    "rowCount": number;
    "duration": time$0.Duration;

    /** Creates a new QueryCompletedPayload instance. */
    constructor($$source: Partial<QueryCompletedPayload> = {}) {
        if (!("queryId" in $$source)) {
            this["queryId"] = "";
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryCompletedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryCompletedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryCompletedPayload($$parsedSource as Partial<QueryCompletedPayload>);
    }
}

/**
 * QueryFailedPayload is emitted when a query fails.
 * Position is the byte offset of the error in the SQL string, if known.
 */
export class QueryFailedPayload {
    "queryId": string;
    "error": string;
    "position"?: number;

    /** Creates a new QueryFailedPayload instance. */
    constructor($$source: Partial<QueryFailedPayload> = {}) {
        if (!("queryId" in $$source)) {
            this["queryId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryFailedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryFailedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryFailedPayload($$parsedSource as Partial<QueryFailedPayload>);
    }
}

/**
 * QueryStartedPayload is emitted when query execution begins.
 * SQLPreview is truncated to 120 characters.
 */
export class QueryStartedPayload {
    "queryId": string;
    "sqlPreview": string;

    /** Creates a new QueryStartedPayload instance. */
    constructor($$source: Partial<QueryStartedPayload> = {}) {
        if (!("queryId" in $$source)) {
            this["queryId"] = "";
        }
        if (!("sqlPreview" in $$source)) {
            this["sqlPreview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryStartedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryStartedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryStartedPayload($$parsedSource as Partial<QueryStartedPayload>);
    }
}

/**
 * Severity classifies the urgency of a Notification event.
 */
export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityInfo = "info",
    SeverityWarning = "warning",
    SeverityError = "error",
};
