// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function LoadEditorState():Promise<string>;

export function LoadSettings():Promise<core.Settings>;

export function SaveEditorState(arg1:string):Promise<void>;

export function SaveSettings(arg1:core.Settings):Promise<void>;
