// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadEditorState() {
  return window['go']['core']['Backend']['LoadEditorState']();
}

export function LoadSettings() {
  return window['go']['core']['Backend']['LoadSettings']();
}

export function SaveEditorState(arg1) {
  return window['go']['core']['Backend']['SaveEditorState'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['core']['Backend']['SaveSettings'](arg1);
}
