// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRow(arg1, arg2, arg3) {
  return window['go']['runners']['Pooler']['AddRow'](arg1, arg2, arg3);
}

export function Close() {
  return window['go']['runners']['Pooler']['Close']();
}

export function GetColumns(arg1, arg2) {
  return window['go']['runners']['Pooler']['GetColumns'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['runners']['Pooler']['GetTables'](arg1);
}

export function Query(arg1, arg2) {
  return window['go']['runners']['Pooler']['Query'](arg1, arg2);
}

export function Run(arg1, arg2, arg3) {
  return window['go']['runners']['Pooler']['Run'](arg1, arg2, arg3);
}
