// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['connections']['ConnectionStore']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['connections']['ConnectionStore']['DeleteConnection'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['connections']['ConnectionStore']['GetConnection'](arg1);
}

export function ListConnections() {
  return window['go']['connections']['ConnectionStore']['ListConnections']();
}

export function LoadConnections() {
  return window['go']['connections']['ConnectionStore']['LoadConnections']();
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['connections']['ConnectionStore']['UpdateConnection'](arg1, arg2);
}
