// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Column represents metadata for a single result column.
 */
export class Column {
    /**
     * Column name
     */
    "name": string;

    /**
     * PostgreSQL type name (e.g., "int4", "varchar")
     */
    "databaseType": string;

    /**
     * PostgreSQL type OID
     */
    "oid": number;

    /**
     * Frontend rendering hint
     */
    "displayType": DisplayType;

    /**
     * Whether column allows NULL (always true for now)
     */
    "nullable": boolean;

    /**
     * Source table OID (0 if not a table column)
     */
    "tableOid": number;

    /**
     * Source column number (0 if not a table column)
     */
    "tableColumn": number;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("databaseType" in $$source)) {
            this["databaseType"] = "";
        }
        if (!("oid" in $$source)) {
            this["oid"] = 0;
        }
        if (!("displayType" in $$source)) {
            this["displayType"] = DisplayType.$zero;
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("tableOid" in $$source)) {
            this["tableOid"] = 0;
        }
        if (!("tableColumn" in $$source)) {
            this["tableColumn"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * DisplayType provides a frontend rendering hint for column data.
 * It maps PostgreSQL's rich type system to common display categories.
 */
export enum DisplayType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * String types (text, varchar, char, etc.)
     */
    DisplayTypeText = "text",

    /**
     * Numeric types (int, float, numeric, etc.)
     */
    DisplayTypeNumber = "number",

    /**
     * Boolean type
     */
    DisplayTypeBoolean = "boolean",

    /**
     * Date/time types (timestamp, date, time, etc.)
     */
    DisplayTypeTimestamp = "timestamp",

    /**
     * JSON and JSONB
     */
    DisplayTypeJSON = "json",

    /**
     * Array types
     */
    DisplayTypeArray = "array",

    /**
     * Bytea and binary data
     */
    DisplayTypeBinary = "binary",

    /**
     * UUID type
     */
    DisplayTypeUUID = "uuid",

    /**
     * Time interval
     */
    DisplayTypeInterval = "interval",

    /**
     * PostGIS geometry types
     */
    DisplayTypeGeometry = "geometry",

    /**
     * Unknown or unsupported types
     */
    DisplayTypeUnknown = "unknown",
};
