// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {runners} from '../models';
import {books} from '../models';

export function AddRow(arg1:connections.Connection,arg2:string,arg3:{[key: string]: any}):Promise<void>;

export function Close():Promise<void>;

export function GetColumns(arg1:connections.Connection,arg2:string):Promise<runners.ColumnResult>;

export function GetTables(arg1:connections.Connection):Promise<runners.TableResult>;

export function Query(arg1:connections.Connection,arg2:string):Promise<runners.QueryResult>;

export function Run(arg1:connections.Connection,arg2:books.Book,arg3:books.Cell):Promise<runners.QueryResult>;
