// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {books} from '../models';

export function Connect(arg1:connections.Connection,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function Run(arg1:connections.Connection,arg2:books.Book,arg3:books.Cell):Promise<string>;
