// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['runners']['Pooler']['Connect'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['runners']['Pooler']['Disconnect'](arg1);
}

export function Run(arg1, arg2, arg3) {
  return window['go']['runners']['Pooler']['Run'](arg1, arg2, arg3);
}
