// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['runners']['Pooler']['Close']();
}

export function Run(arg1, arg2, arg3) {
  return window['go']['runners']['Pooler']['Run'](arg1, arg2, arg3);
}
