// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Block is a single content unit within a section.
 */
export class Block {
    "id": string;
    "type": BlockType;
    "content": string;

    /**
     * 0 = use default 50
     */
    "pageSize"?: number;

    /** Creates a new Block instance. */
    constructor($$source: Partial<Block> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = BlockType.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Block instance from a string or object.
     */
    static createFrom($$source: any = {}): Block {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Block($$parsedSource as Partial<Block>);
    }
}

/**
 * BlockType discriminates between markdown and query blocks.
 */
export enum BlockType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BlockMarkdown = "markdown",
    BlockQuery = "query",
};

/**
 * Book is the top-level container representing a .sql SequelBook file.
 */
export class Book {
    "id": string;
    "title": string;
    "connection"?: string;
    "chapters": Chapter[];

    /** Creates a new Book instance. */
    constructor($$source: Partial<Book> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("chapters" in $$source)) {
            this["chapters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Book instance from a string or object.
     */
    static createFrom($$source: any = {}): Book {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chapters" in $$parsedSource) {
            $$parsedSource["chapters"] = $$createField3_0($$parsedSource["chapters"]);
        }
        return new Book($$parsedSource as Partial<Book>);
    }
}

/**
 * Chapter groups sections, optionally overriding the book-level connection.
 */
export class Chapter {
    "id": string;
    "title": string;
    "connection"?: string;
    "sections": Section[];

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sections" in $$source)) {
            this["sections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField3_0($$parsedSource["sections"]);
        }
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

/**
 * OpenBook represents a book that is currently open in the application.
 */
export class OpenBook {
    "book": Book | null;

    /**
     * empty = never saved (new book)
     */
    "filePath": string;

    /**
     * true = modified since last save
     */
    "dirty": boolean;

    /** Creates a new OpenBook instance. */
    constructor($$source: Partial<OpenBook> = {}) {
        if (!("book" in $$source)) {
            this["book"] = null;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenBook instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenBook {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("book" in $$parsedSource) {
            $$parsedSource["book"] = $$createField0_0($$parsedSource["book"]);
        }
        return new OpenBook($$parsedSource as Partial<OpenBook>);
    }
}

/**
 * Section groups related blocks under a title.
 */
export class Section {
    "id": string;
    "title": string;
    "blocks": Block[];

    /** Creates a new Section instance. */
    constructor($$source: Partial<Section> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Section instance from a string or object.
     */
    static createFrom($$source: any = {}): Section {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField2_0($$parsedSource["blocks"]);
        }
        return new Section($$parsedSource as Partial<Section>);
    }
}

// Private type creation functions
const $$createType0 = Chapter.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Section.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Book.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Block.createFrom;
const $$createType7 = $Create.Array($$createType6);
