// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";

/**
 * Config holds app-level preferences.
 */
export class Config {
    /**
     * default: 200
     */
    "pageSize": number;

    /**
     * default: ~/.sequelbook/books/
     */
    "booksDir": string;

    /**
     * default: 14
     */
    "fontSize": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("booksDir" in $$source)) {
            this["booksDir"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ConnectionEntry is a saved connection configuration.
 * Type defaults to "postgres" when empty. For SQLite, Database is the file path.
 */
export class ConnectionEntry {
    /**
     * con_<xid>, assigned on save
     */
    "id": string;

    /**
     * user-visible label
     */
    "name": string;

    /**
     * postgres | mysql | sqlite; default postgres
     */
    "type": string;
    "host": string;
    "port": number;
    "database": string;
    "user": string;

    /**
     * plaintext for MVP 0
     */
    "password": string;
    "sslMode": string;
    "ssh"?: connection$0.SSHTunnelConfig | null;

    /** Creates a new ConnectionEntry instance. */
    constructor($$source: Partial<ConnectionEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionEntry {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField9_0($$parsedSource["ssh"]);
        }
        return new ConnectionEntry($$parsedSource as Partial<ConnectionEntry>);
    }
}

// Private type creation functions
const $$createType0 = connection$0.SSHTunnelConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
