// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';

export function CreateConnection(arg1:connections.ConnectionData):Promise<connections.Connection>;

export function DeleteConnection(arg1:string):Promise<void>;

export function GetConnection(arg1:string):Promise<connections.Connection|boolean>;

export function ListConnections():Promise<Array<connections.Connection>>;

export function LoadConnections():Promise<void>;

export function UpdateConnection(arg1:string,arg2:connections.ConnectionData):Promise<connections.Connection>;
